### PR TITLE
Fix shaka ready state handling

### PR DESCRIPTION
**Pull request by tchakabam**
- avoid errors when Shaka player is not ready yet to take calls
- fix bug: _ready gets called from parent container. we should do a no-op (or not override?)
- either way, we trigger readiness on Shaka readiness

### CODE REVIEW

**Comment by tchakabam** [comment]
Great, the more people check the better. Thanks!

What I believe is happening is that Clappr `Playback` abstract implementation calls the `_ready` function in sync with the readiness of the `Player`. now the Shaka readiness is async because it needs init of MediaSource and SourceBuffers. 

Thus the ShakaPlayback will only be ready once the MediaSource is ready. 

Obviously the `HTML5Playback` readiness per-se is not async so we can be confident about that being ready before Shaka instance.

Hope that explanation makes sense :) or let me know if i got something wrong.

**Comment by tchakabam** [comment]
I think this is fixing a bug that has actually been introduced with https://github.com/clappr/dash-shaka-playback/pull/38 in the first place.

@vagnervjs can you explain? can we try to fix both issues? :)

**Comment by vagnervjs** [comment]
I did not realize that there would be a problem overriding the `_ready` method, but now I agree that it should be no-op to avoid these problems.
Both issues (#38 and ready control) are fixed in this PR, so, LGTM :)

Thanks for the attention @tchakabam

**Comment by tchakabam** [comment]
Awesome! :beers:

**Pull request merged**
