### PR TITLE
add external unminified build. rename build artifacts to .external.js

### PR DESCRIPTION
**Pull request by tchakabam**

### CODE REVIEW

**Comment by leandromoreira** [comment]
can you @kslimani review this? :)

**Comment by kslimani** [comment]
LGTM. Just  one point : @tchakabam do you require that `dash-shaka-playback.external.js` unminified bundle to be compiled if running webpack-dev-server ? (ie: `npm start`).

If yes, then it's all good. !
If not, you just need to modify the condition to add configuration, for example, if NPM_RUN = 'build'

**Comment by tchakabam** [comment]
i think that generally it's a good concept if webpack dev-server produces just the same as the usual webpack build. so, yes :) 

thanks for the quick review :) 

however, generally @leandromoreira @kslimani i feel like we lack a general concept of how to build good Clappr plugins. Decisions may have been made without really having discussed how functional they may be. Some questions are:

- What should the main NPM package file point to? Currently it is a bundle with the external dependency built-in, that we are "plugging". However usually when including a package via NPM main, we do it via some require function (webpack, browserify,..) that references the main script in the respective node_module and in that specific case we might actually rather want the external package? Food for thought... Happy to hear what you guys think.

- When using a fully bundle package it is rather for including it as a script tag on an HTML page? So no need to have it as NPM main script?

- Generally, should we not ship the `external` build (how its done now). Why not?

- How do we deal with releases? How about we have a CI set up?

**Comment by tchakabam** [comment]
And btw, very happy to work with you guys on this very plugin :)

**Comment by kslimani** [comment]
You are correct for `package.json` "main" field. It still point to bundle with shaka for backward compatibility reason. I am not against changing this, but if it is done, it should be (imho) also coming with release version bump.

**Comment by leandromoreira** [comment]
thank you both @tchakabam and @kslimani you're awesome! 🍻 🍻 🍻 🍻

**Pull request merged**
